export const LOG_DRAW_CODES = {
  GET_USER_SUCCESS: 'DRAW_000',
  GET_USER_ERROR: 'DRAW_100',
  GET_ALL_SUCCESS: 'DRAW_001',
  GET_ALL_ERROR: 'DRAW_101',
  GET_BY_ID_SUCCESS: 'DRAW_002',
  GET_BY_ID_ERROR: 'DRAW_102',
  CREATE_SUCCESS: 'DRAW_003',
  CREATE_ERROR: 'DRAW_103',
  UPDATE_SUCCESS: 'DRAW_004',
  UPDATE_ERROR: 'DRAW_104',
  DELETE_SUCCESS: 'DRAW_005',
  DELETE_ERROR: 'DRAW_105',
};
