export enum SqlServerDataTypes {
    INT = 'int',
    BIGINT = 'bigint',
    SMALLINT = 'smallint',
    TINYINT = 'tinyint',
    BIT = 'bit',
    DECIMAL = 'decimal',
    NUMERIC = 'numeric',
    FLOAT = 'float',
    REAL = 'real',
    MONEY = 'money',
    SMALLMONEY = 'smallmoney',
    CHAR = 'char',
    VARCHAR = 'varchar',
    TEXT = 'text',
    NCHAR = 'nchar',
    NVARCHAR = 'nvarchar',
    NTEXT = 'ntext',
    DATE = 'date',
    TIME = 'time',
    DATETIME = 'datetime',
    DATETIME2 = 'datetime2',
    DATETIMEOFFSET = 'datetimeoffset',
    SMALLDATETIME = 'smalldatetime',
    UNIQUEIDENTIFIER = 'uniqueidentifier',
    BINARY = 'binary',
    VARBINARY = 'varbinary',
    IMAGE = 'image',
    XML = 'xml',
    SQL_VARIANT = 'sql_variant',
    GEOGRAPHY = 'geography',
    GEOMETRY = 'geometry',
    HIERARCHYID = 'hierarchyid'
  }
  